const data = {
    products : [
        {
            name : "Puma Shoe",
            slug : "puma-shoe",
            category : "Shoes",
            image : "/images/image.jpg",
            price : 999,
            countInStock : 10,
            brand : "Puma",
            rating : 4.5,
            numReviews : 10,
            description : "high quality shoe",
        },
        {
            name : "Nike Shoe",
            slug : "nike-shoe",
            category : "Shoes",
            image : "/images/image.jpg",
            price : 1199,
            countInStock : 10,
            brand : "Nike",
            rating : 4.5,
            numReviews : 10,
            description : "high quality shoe",
        },
        {
            name : "Bata Shoe",
            slug : "bata-shoe",
            category : "Shoes",
            image : "/images/image.jpg",
            price : 999,
            countInStock : 10,
            brand : "Bata",
            rating : 4.5,
            numReviews : 10,
            description : "high quality shoe",
        },
        {
            name : "Lee Shirt",
            slug : "lee-shirt",
            category : "Shirts",
            image : "/images/image.jpg",
            price : 799,
            countInStock : 10,
            brand : "Lee",
            rating : 4.5,
            numReviews : 10,
            description : "high quality shirt",
        },
    ],
}

export default data;